
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-7
pull_requests: [{"author":{"id":"MDQ6VXNlcjg2OTg1OTQx","is_bot":false,"login":"mczimmermann","name":"Michelle Z"},"headRefName":"che-copied-files","number":68,"title":"copied files for Articles from team02","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/68"},{"author":{"id":"U_kgDOBYEQGw","is_bot":false,"login":"nadavital","name":"Nadav Avital"},"headRefName":"nadav-copied-files","number":66,"title":"added menuItemReview.json","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/66"},{"author":{"id":"MDQ6VXNlcjUyOTMyMjQ1","is_bot":false,"login":"rkibel","name":"Ron Kibel"},"headRefName":"ron-copied-files","number":65,"title":"Copy HelpRequest files from team02","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/65"}]
