
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-7
pull_requests: [{"author":{"id":"MDQ6VXNlcjE3MDE2NTI4","is_bot":false,"login":"chendashi","name":"Zheli Chen"},"headRefName":"chloe-table","number":80,"title":"add Table, Table tests, Table tests utils, and fixed storybook","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/80"},{"author":{"id":"MDQ6VXNlcjE3MDE2NTI4","is_bot":false,"login":"chendashi","name":"Zheli Chen"},"headRefName":"chloe-form","number":79,"title":"Add Form for DiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/79"},{"author":{"id":"MDQ6VXNlcjMyMTUwMjk5","is_bot":false,"login":"james-y-f","name":"James Fu"},"headRefName":"james-RecReq-fixtures","number":78,"title":"Added fixtures for Rec Requests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/78"},{"author":{"id":"MDQ6VXNlcjg2OTg1OTQx","is_bot":false,"login":"mczimmermann","name":"Michelle Z"},"headRefName":"che-form","number":77,"title":"Creating articles form and stories","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/77"},{"author":{"id":"MDQ6VXNlcjMyMTUwMjk5","is_bot":false,"login":"james-y-f","name":"James Fu"},"headRefName":"james-RecReq-backend","number":75,"title":"CRUD operations from team02 for Rec Requests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/75"}]
