
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-7
pull_requests: [{"author":{"id":"MDQ6VXNlcjg2OTg1OTQx","is_bot":false,"login":"mczimmermann","name":"Michelle Z"},"headRefName":"che-create","number":103,"title":"Created ArticlesReview Create Page","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/103"},{"author":{"id":"MDQ6VXNlcjMyMTUwMjk5","is_bot":false,"login":"james-y-f","name":"James Fu"},"headRefName":"james-RecReq-form","number":102,"title":"Added Rec Request form with tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/102"},{"author":{"id":"MDQ6VXNlcjg2OTg1OTQx","is_bot":false,"login":"mczimmermann","name":"Michelle Z"},"headRefName":"che-table","number":101,"title":"Creating articles table and stories","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/101"}]
