
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-7
pull_requests: [{"author":{"id":"U_kgDOBYEQGw","is_bot":false,"login":"nadavital","name":"Nadav Avital"},"headRefName":"nadav-h05","number":114,"title":"Completed MenuItemReview Integration and E2E Tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/114"},{"author":{"id":"MDQ6VXNlcjE3MDE2NTI4","is_bot":false,"login":"chendashi","name":"Zheli Chen"},"headRefName":"chloe-h05","number":113,"title":"DiningCommonsMenuItem IT and Web Testing","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/113"},{"author":{"id":"U_kgDOBanq-A","is_bot":false,"login":"YixinXue","name":"The boyhood"},"headRefName":"Yixin-hw5","number":112,"title":"Yixin hw5 integration and end-to-end test for UCSBOrganization","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/112"},{"author":{"id":"MDQ6VXNlcjUyOTMyMjQ1","is_bot":false,"login":"rkibel","name":"Ron Kibel"},"headRefName":"rkibel-h05","number":111,"title":"HelpRequest Integration and End-to-End","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/111"},{"author":{"id":"MDQ6VXNlcjg2OTg1OTQx","is_bot":false,"login":"mczimmermann","name":"Michelle Z"},"headRefName":"che-testing","number":110,"title":"mz - Articles Integration and Web Testing ","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/110"},{"author":{"id":"MDQ6VXNlcjMyMTUwMjk5","is_bot":false,"login":"james-y-f","name":"James Fu"},"headRefName":"james-RecReq-placeholder","number":109,"title":"added rec req placeholder","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/109"},{"author":{"id":"MDQ6VXNlcjMyMTUwMjk5","is_bot":false,"login":"james-y-f","name":"James Fu"},"headRefName":"james-RecReq-table","number":107,"title":"added table for Recomemndation Requests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/107"}]
