
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-7
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-7
pull_requests: [{"author":{"id":"MDQ6VXNlcjg2OTg1OTQx","is_bot":false,"login":"mczimmermann","name":"Michelle Z"},"headRefName":"che-index","number":105,"title":"adding all functionality for articles index page","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/105"},{"author":{"id":"MDQ6VXNlcjg2OTg1OTQx","is_bot":false,"login":"mczimmermann","name":"Michelle Z"},"headRefName":"che-edit2","number":104,"title":"adding all functionality for edit, passes tests and mutations","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-7/pull/104"}]
